version: '3.7'
services:
  app:
    image: gateway-laravel
    build:
      context: ./
      args:
        user: instock
        uid: 1000
        build: dev
      dockerfile: ./dockerfile
    container_name: gateway-laravel
    restart: unless-stopped
    ports:
      - 8082:80
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    depends_on:
      - db
    links:
      - db
    networks:
      - localNetwork

  db:
    image: mysql:5.7
    container_name: gateway-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql/init:/docker-entrypoint-initdb.d
      - ./docker-compose/mysql/data:/var/lib/mysql:delegated
    networks:
      - localNetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gateway-mysql
    restart: unless-stopped
    expose:
      - 80
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    networks:
      - localNetwork
networks:
  localNetwork:
    driver: bridge
