version: "3.1"

networks:
  app-network:
    driver: bridge

services:
  app:
    image: runnable/php:5.6.27-apache
    depends_on:
      - db
    links:
      - db
    ports:
      - 8082:80
    restart: always
    env_file:
      - .env  
    volumes:
      - ./src:/var/www/html:rw
      - ./docker/000-laravel.conf:/etc/apache2/sites-enabled/000-laravel.conf
      - ./docker/apache2.conf:/etc/apache2/apache2.conf
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql:delegated
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    expose:
      - 80
    ports:
      - 8080:80
    networks:
      - app-network
        

volumes:
  myDataVolume:
    external: false
    name: myDataVolume_test